### ISSUE TITLE
Spawn fails after starting normal notebook

### ISSUE THREAD

**Issue by alex-translation** [microsoft/planetary-computer-hub#64]
<img width="1190" alt="Screen Shot 2022-05-19 at 10 42 35 AM" src="https://user-images.githubusercontent.com/82901988/169370267-623dfa99-4a64-4f16-b7e9-6af3904baf00.png">

Hello,

I recently started using planetary computer and loved it, until I ran into the same issue yesterday and today. I didn't do anything differently than before, but can't seem to avoid this problem. The final output reads, "Spawn failed: Server ... didn't respond in 30 seconds."

Is there some debugging I can do on my end?

Thanks,
Alex

**Comment by TomAugspurger** [comment]
This sometimes happens if you've filled up your home directory. Can you send an email to planetarycomputer@microsoft.com with the account you used to sign up for the Planetary Compujter and I can check.

**Comment by TomAugspurger** [comment]
Continuing via email, closing here.
