### ISSUE TITLE
 The Planetary Computer Hub(Pytorch mode) fail to start up

### ISSUE THREAD

**Issue by hongxrsysu** [microsoft/planetary-computer-hub#72]
Planetary computer hub(Pytorch mode) cannot be opened for two consecutive days. It always report errors: Spawn failed: Timeout
![image](https://user-images.githubusercontent.com/81839570/210910121-84ebcfca-668d-47fc-9a50-9f480fbe2135.png)

It says that there is not enough CPU, GPU and memory. I think it is the server's problem. I make sure that my network is normal and can be opened normally two days ago. How to solve this problem?
Thanks！！

**Comment by TomAugspurger** [comment]
Just to confirm: are you able to start a non-GPU server?

Our Hub deployment has a fixed number of GPU nodes available.  Most likely all the slots were taken when you've tried signing in :/

**Comment by hongxrsysu** [comment]
> Just to confirm: are you able to start a non-GPU server?
> 
> Our Hub deployment has a fixed number of GPU nodes available. Most likely all the slots were taken when you've tried signing in :/

Thanks! I can start a CPU server. Maybe I can try again later to see if I can start a GPU server successfully, right?

**Comment by TomAugspurger** [comment]
Yep.
________________________________
